// !!! DO NOT EDIT !!! Generated by build/generate.zig

const std = @import("std");
const lib = @import("lib.zig");

pub const STAR = "*";
pub const TEXT = "text";
pub const IMAGE = "image";
pub const AUDIO = "audio";
pub const VIDEO = "video";
pub const APPLICATION = "application";
pub const MULTIPART = "multipart";
pub const MESSAGE = "message";
pub const MODEL = "model";
pub const FONT = "font";
pub const PLAIN = "plain";
pub const HTML = "html";
pub const XML = "xml";
pub const JAVASCRIPT = "javascript";
pub const CSS = "css";
pub const CSV = "csv";
pub const EVENT_STREAM = "event-stream";
pub const VCARD = "vcard";
pub const TAB_SEPARATED_VALUES = "tab-separated-values";
pub const JSON = "json";
pub const WWW_FORM_URLENCODED = "x-www-form-urlencoded";
pub const MSGPACK = "msgpack";
pub const OCTET_STREAM = "octet-stream";
pub const PDF = "pdf";
pub const WOFF = "woff";
pub const WOFF2 = "woff2";
pub const FORM_DATA = "form-data";
pub const BMP = "bmp";
pub const GIF = "gif";
pub const JPEG = "jpeg";
pub const PNG = "png";
pub const SVG = "svg+xml";
pub const BASIC = "basic";
pub const MPEG = "mpeg";
pub const MP4 = "mp4";
pub const OGG = "ogg";
pub const CHARSET = "charset";
pub const BOUNDARY = "boundary";

pub const Atom = enum(u8) {
    TEXT_PLAIN,
    TEXT_PLAIN_UTF_8,
    TEXT_HTML,
    TEXT_HTML_UTF_8,
    TEXT_CSS,
    TEXT_CSS_UTF_8,
    TEXT_JAVASCRIPT,
    TEXT_XML,
    TEXT_EVENT_STREAM,
    TEXT_CSV,
    TEXT_CSV_UTF_8,
    TEXT_TAB_SEPARATED_VALUES,
    TEXT_TAB_SEPARATED_VALUES_UTF_8,
    TEXT_VCARD,
    IMAGE_JPEG,
    IMAGE_GIF,
    IMAGE_PNG,
    IMAGE_BMP,
    IMAGE_SVG,
    FONT_WOFF,
    FONT_WOFF2,
    APPLICATION_JSON,
    APPLICATION_JAVASCRIPT,
    APPLICATION_JAVASCRIPT_UTF_8,
    APPLICATION_WWW_FORM_URLENCODED,
    APPLICATION_OCTET_STREAM,
    APPLICATION_MSGPACK,
    APPLICATION_PDF,
    APPLICATION_DNS,
    STAR_STAR,
    TEXT_STAR,
    IMAGE_STAR,
    VIDEO_STAR,
    AUDIO_STAR,

    pub fn source(self: Atom) lib.Source {
        return switch (self) {
            .TEXT_PLAIN => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/plain",
                },
            },
            .TEXT_PLAIN_UTF_8 => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/plain; charset=utf-8",
                },
            },
            .TEXT_HTML => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/html",
                },
            },
            .TEXT_HTML_UTF_8 => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/html; charset=utf-8",
                },
            },
            .TEXT_CSS => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/css",
                },
            },
            .TEXT_CSS_UTF_8 => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/css; charset=utf-8",
                },
            },
            .TEXT_JAVASCRIPT => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/javascript",
                },
            },
            .TEXT_XML => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/xml",
                },
            },
            .TEXT_EVENT_STREAM => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/event-stream",
                },
            },
            .TEXT_CSV => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/csv",
                },
            },
            .TEXT_CSV_UTF_8 => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/csv; charset=utf-8",
                },
            },
            .TEXT_TAB_SEPARATED_VALUES => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/tab-separated-values",
                },
            },
            .TEXT_TAB_SEPARATED_VALUES_UTF_8 => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/tab-separated-values; charset=utf-8",
                },
            },
            .TEXT_VCARD => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/vcard",
                },
            },
            .IMAGE_JPEG => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "image/jpeg",
                },
            },
            .IMAGE_GIF => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "image/gif",
                },
            },
            .IMAGE_PNG => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "image/png",
                },
            },
            .IMAGE_BMP => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "image/bmp",
                },
            },
            .IMAGE_SVG => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "image/svg+xml",
                },
            },
            .FONT_WOFF => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "font/woff",
                },
            },
            .FONT_WOFF2 => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "font/woff2",
                },
            },
            .APPLICATION_JSON => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "application/json",
                },
            },
            .APPLICATION_JAVASCRIPT => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "application/javascript",
                },
            },
            .APPLICATION_JAVASCRIPT_UTF_8 => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "application/javascript; charset=utf-8",
                },
            },
            .APPLICATION_WWW_FORM_URLENCODED => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "application/x-www-form-urlencoded",
                },
            },
            .APPLICATION_OCTET_STREAM => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "application/octet-stream",
                },
            },
            .APPLICATION_MSGPACK => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "application/msgpack",
                },
            },
            .APPLICATION_PDF => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "application/pdf",
                },
            },
            .APPLICATION_DNS => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "application/dns-message",
                },
            },
            .STAR_STAR => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "*/*",
                },
            },
            .TEXT_STAR => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "text/*",
                },
            },
            .IMAGE_STAR => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "image/*",
                },
            },
            .VIDEO_STAR => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "video/*",
                },
            },
            .AUDIO_STAR => lib.Source{
                .Atom = .{
                    .atom = @enumToInt(self),
                    .text = "audio/*",
                },
            },
        };
    }
};

pub const TEXT_PLAIN: lib.Mime = .{
    .source = Atom.source(.TEXT_PLAIN),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const TEXT_PLAIN_UTF_8: lib.Mime = .{
    .source = Atom.source(.TEXT_PLAIN_UTF_8),
    .slash = 4,
    .plus = null,
    .params = .{ .Utf8 = 10 },
};

pub const TEXT_HTML: lib.Mime = .{
    .source = Atom.source(.TEXT_HTML),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const TEXT_HTML_UTF_8: lib.Mime = .{
    .source = Atom.source(.TEXT_HTML_UTF_8),
    .slash = 4,
    .plus = null,
    .params = .{ .Utf8 = 9 },
};

pub const TEXT_CSS: lib.Mime = .{
    .source = Atom.source(.TEXT_CSS),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const TEXT_CSS_UTF_8: lib.Mime = .{
    .source = Atom.source(.TEXT_CSS_UTF_8),
    .slash = 4,
    .plus = null,
    .params = .{ .Utf8 = 8 },
};

pub const TEXT_JAVASCRIPT: lib.Mime = .{
    .source = Atom.source(.TEXT_JAVASCRIPT),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const TEXT_XML: lib.Mime = .{
    .source = Atom.source(.TEXT_XML),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const TEXT_EVENT_STREAM: lib.Mime = .{
    .source = Atom.source(.TEXT_EVENT_STREAM),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const TEXT_CSV: lib.Mime = .{
    .source = Atom.source(.TEXT_CSV),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const TEXT_CSV_UTF_8: lib.Mime = .{
    .source = Atom.source(.TEXT_CSV_UTF_8),
    .slash = 4,
    .plus = null,
    .params = .{ .Utf8 = 8 },
};

pub const TEXT_TAB_SEPARATED_VALUES: lib.Mime = .{
    .source = Atom.source(.TEXT_TAB_SEPARATED_VALUES),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const TEXT_TAB_SEPARATED_VALUES_UTF_8: lib.Mime = .{
    .source = Atom.source(.TEXT_TAB_SEPARATED_VALUES_UTF_8),
    .slash = 4,
    .plus = null,
    .params = .{ .Utf8 = 25 },
};

pub const TEXT_VCARD: lib.Mime = .{
    .source = Atom.source(.TEXT_VCARD),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const IMAGE_JPEG: lib.Mime = .{
    .source = Atom.source(.IMAGE_JPEG),
    .slash = 5,
    .plus = null,
    .params = .None,
};

pub const IMAGE_GIF: lib.Mime = .{
    .source = Atom.source(.IMAGE_GIF),
    .slash = 5,
    .plus = null,
    .params = .None,
};

pub const IMAGE_PNG: lib.Mime = .{
    .source = Atom.source(.IMAGE_PNG),
    .slash = 5,
    .plus = null,
    .params = .None,
};

pub const IMAGE_BMP: lib.Mime = .{
    .source = Atom.source(.IMAGE_BMP),
    .slash = 5,
    .plus = null,
    .params = .None,
};

pub const IMAGE_SVG: lib.Mime = .{
    .source = Atom.source(.IMAGE_SVG),
    .slash = 5,
    .plus = 9,
    .params = .None,
};

pub const FONT_WOFF: lib.Mime = .{
    .source = Atom.source(.FONT_WOFF),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const FONT_WOFF2: lib.Mime = .{
    .source = Atom.source(.FONT_WOFF2),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const APPLICATION_JSON: lib.Mime = .{
    .source = Atom.source(.APPLICATION_JSON),
    .slash = 11,
    .plus = null,
    .params = .None,
};

pub const APPLICATION_JAVASCRIPT: lib.Mime = .{
    .source = Atom.source(.APPLICATION_JAVASCRIPT),
    .slash = 11,
    .plus = null,
    .params = .None,
};

pub const APPLICATION_JAVASCRIPT_UTF_8: lib.Mime = .{
    .source = Atom.source(.APPLICATION_JAVASCRIPT_UTF_8),
    .slash = 11,
    .plus = null,
    .params = .{ .Utf8 = 22 },
};

pub const APPLICATION_WWW_FORM_URLENCODED: lib.Mime = .{
    .source = Atom.source(.APPLICATION_WWW_FORM_URLENCODED),
    .slash = 11,
    .plus = null,
    .params = .None,
};

pub const APPLICATION_OCTET_STREAM: lib.Mime = .{
    .source = Atom.source(.APPLICATION_OCTET_STREAM),
    .slash = 11,
    .plus = null,
    .params = .None,
};

pub const APPLICATION_MSGPACK: lib.Mime = .{
    .source = Atom.source(.APPLICATION_MSGPACK),
    .slash = 11,
    .plus = null,
    .params = .None,
};

pub const APPLICATION_PDF: lib.Mime = .{
    .source = Atom.source(.APPLICATION_PDF),
    .slash = 11,
    .plus = null,
    .params = .None,
};

pub const APPLICATION_DNS: lib.Mime = .{
    .source = Atom.source(.APPLICATION_DNS),
    .slash = 11,
    .plus = null,
    .params = .None,
};

pub const STAR_STAR: lib.Mime = .{
    .source = Atom.source(.STAR_STAR),
    .slash = 1,
    .plus = null,
    .params = .None,
};

pub const TEXT_STAR: lib.Mime = .{
    .source = Atom.source(.TEXT_STAR),
    .slash = 4,
    .plus = null,
    .params = .None,
};

pub const IMAGE_STAR: lib.Mime = .{
    .source = Atom.source(.IMAGE_STAR),
    .slash = 5,
    .plus = null,
    .params = .None,
};

pub const VIDEO_STAR: lib.Mime = .{
    .source = Atom.source(.VIDEO_STAR),
    .slash = 5,
    .plus = null,
    .params = .None,
};

pub const AUDIO_STAR: lib.Mime = .{
    .source = Atom.source(.AUDIO_STAR),
    .slash = 5,
    .plus = null,
    .params = .None,
};
